[네트워크] 네트워크 발표자료 통합본
BCS-study/basic-computer-science pull request #11
Opened 2024-04-12 12:51 UTC by OhHaneol

2024-04-12 14:17 UTC, minsu111 commented
정리 감사합니다 고생하셨어요 👍
몇 가지 사소한 수정사항 발견해서 코멘트 남겨두었습니다~

2024-04-12 14:27 UTC, minsu111 approved these changes
정리 감사합니다 고생하셨어요 👍
몇 가지 사소한 수정사항만 코멘트 남겨두었습니다~

2024-04-12 14:27 UTC, minsu111 commented on Computer Science/Network/1. 네트워크의 기초.md
> +    - 고성능 네트워크는 수익 창출과 운영 효율성에 직접적인 영향을 미친다. 처리량이 적고 지연 시간이 긴 네트워크는 많은 양의 데이터를 전송 및 처리하는 데 어려움을 겪으며 이로 인해 정체가 발생하고 애플리케이션 성능이 저하된다. 반대로 처리량이 많고 지연 시간이 짧은 네트워크는 반응성이 뛰어나고 효율적이다.
해당 문장도 다른 문장들과 같이 '~다.' 체로 통일하면 좋을 것 같아요!

2024-04-12 14:27 UTC, minsu111 commented on Computer Science/Network/1. 네트워크의 기초.md
> +    - 정의 : 하이브리드 토폴로지는 두개 이상의 서로 다른 토폴로지가 결합된 네트워크 형태를 뜻한다.
해당 부분도 마찬가지로 문체 통일하면 좋을 것 같습니다.

2024-04-12 14:27 UTC, minsu111 commented on Computer Science/Network/1. 네트워크의 기초.md
> +**병목 현상**
병목 현상 -> 이부분 개행하거나 헤더 태그로 넣어야 할 것 같아요

2024-04-12 14:27 UTC, minsu111 commented on Computer Science/Network/1. 네트워크의 기초.md
> +- **응용 사례**:
응용 사례 -> 이부분 잘못 들어간 것 같아요!

2024-04-12 16:13 UTC, k2645 requested changes
수고하셨습니다 :)

2024-04-12 16:13 UTC, k2645 commented on Computer Science/Network/1. 네트워크의 기초.md
> +- `ICMP` : 인터넷 제어 메시지 프로토콜. 프로토콜 네트워크 장치에서 네트워크 통신 문제를 진단하는데 사용되는 네트워크 계층 프로토콜
핵심 용어의 용어들을 코드로 처리할지 볼드체로 처리할지 정하면 좋을 것 같습니다!
그리고 TCP/IP에만 온점이 있는데 이건 삭제해주시면 감사하겠습니다.

2024-04-12 16:13 UTC, k2645 commented on Computer Science/Network/1. 네트워크의 기초.md
> +        ```
Linux환경에서는 패킷을 여러번 보내는 옵션의 단축키가 `-n`이 아닌 `-c`였습니다. 단축키의 경우 윈도우 체제랑 Linux가 많이 다른 것 같으니 이 점도 같이 적어주시면 더 좋을 것 같습니다.

2024-04-12 16:13 UTC, k2645 commented on Computer Science/Network/1. 네트워크의 기초.md
> +- 그 밖의 명령어, 프로그램
마크다운 형식으로 변환시켰을 때 오류?가 뜨는 것 같습니다. 수정해주시면 감사하겠습니다!

2024-04-13 07:35 UTC, OhHaneol commented
@minsu111 말씀하신 내용 반영했습니다! 제가 급하게 하느라 놓친 게 많은데 피드백 감사합니다😃
@k2645 말씀하신 부분 반영했습니다! 피드백 감사합니다😃

2024-04-14 05:33 UTC, k2645 approved these changes
수고하셨습니다.ᐟ.ᐟ

2024-04-15 02:30 UTC, NewCodes7 approved these changes
정리하느라 수고하셨습니다!! 잘 읽었습니다!

2024-04-15 02:30 UTC, NewCodes7 commented on Computer Science/Network/1. 네트워크의 기초.md
> +- `네트워크`: 노드(네트워크 장치)와 링크(유선, 무선) 가 서로 연결되어리소스를 공유하는 집합
연결되어리소스를 -> 연결되어 리소스를

띄어쓰기 부탁드립니다!

2024-04-15 02:30 UTC, NewCodes7 commented on Computer Science/Network/1. 네트워크의 기초.md
> +- `네트워크`: 노드(네트워크 장치)와 링크(유선, 무선) 가 서로 연결되어리소스를 공유하는 집합
링크(유선, 무선) 가 -> 링크(유선, 무선)가

2024-04-15 02:30 UTC, NewCodes7 commented on Computer Science/Network/1. 네트워크의 기초.md
> +- **응용 사례**: 지연 시간이 길어지면 어떻게 할까요? 대역폭이 넓은 네트워크에서는 처리량이 높고 지연 시간이 낮습니다. 따라서 지연 시간이 길어질 경우 대역폭을 증가시켜 해결할 수 있습니다.
이러한 응용 사례 항목 좋네요!!

2024-04-15 02:30 UTC, NewCodes7 commented on Computer Science/Network/1. 네트워크의 기초.md
> +    - 고성능 네트워크는 수익 창출과 운영 효율성에 직접적인 영향을 미칩니다. 예시로 처리량이 적고 지연 시간이 긴 네트워크는 많은 양의 데이터를 전송 및 처리하는 데 어려움을 겪으며, 이로 인해 정체가 발생하고 애플리케이션 성능이 저하됩니다. 반대로 처리량이 많고 지연 시간이 짧은 네트워크는 반응성이 뛰어나고 효율적입니다.
이것도 좋네요!! 개념 설명에서 끝나는 게 아니라 필요한 이유까지!

2024-04-15 02:30 UTC, NewCodes7 commented on Computer Science/Network/1. 네트워크의 기초.md
> -  - [온라인 강의](링크)
링크 없으면 빼주셔도 될 것 같네요!

2024-04-15 02:30 UTC, NewCodes7 commented on Computer Science/Network/1. 네트워크의 기초.md
> +    - [깃허브](링크)
링크 없으면 빼주셔도 될 것 같네요!

2024-04-15 02:30 UTC, NewCodes7 commented on Computer Science/Network/1. 네트워크의 기초.md
템플릿에 포함된 내용은 아니었지만, 목차를 추가해주시면 나중에 다시 모르는 개념 찾아볼 때 or 문서를 본격적으로 보기 전에 거시적으로 어떤 내용이 들어있는지 확인할 때 도움이 될 것 같습니다!!

목차 만들어주는 툴을 첨부드립니다! vscode 사용하신다면 플러그인이 유용하실 겁니다!

1. https://ecotrust-canada.github.io/markdown-toc/
2. vscode 플러그인(Auto Markdown TOC): https://marketplace.visualstudio.com/items?itemName=xavierguarch.auto-markdown-toc

2024-04-16 08:00 UTC, merged