[네트워크] 네트워크의 기기 자료 총정리
BCS-study/basic-computer-science pull request #12
Opened 2024-04-12 13:10 UTC by NewCodes7

물리적인 기기를 다루는 내용인지라 이미지도 조금 추가해봤습니다!
사소한 거라도 좋으니 피드백 주실만한 거 있으면 남겨주세요!!

2024-04-12 13:56 UTC, OhHaneol approved these changes
스위치에 대한 추가 학습이 따로 정리돼서 좋습니다!

2024-04-12 14:24 UTC, minsu111 commented
이미지 추가되니 좋네요! 고생하셨습니다 👍

2024-04-12 14:26 UTC, minsu111 approved these changes
이미지 추가되니 좋네요! 고생하셨습니다 👍

2024-04-12 16:26 UTC, k2645 requested changes
스위치에 대한 추가적인 내용을 넣어주셔서 더 깊이있게 공부할 수 있을 것 같습니다! 정말 수고 많으셨습니다.ᐟ.ᐟ

2024-04-12 16:26 UTC, k2645 commented on Computer Science/Network/3. 네트워크의 기기.md
> +- 스위칭은 정보 전달의 수단과 회선의 효율적 운용을 위해 입출력 사태를 감시하며, 전송로의 장애 발생 시 현재 상태에서 예비 상태로 전환한다.
해당 내용들은 스위치의 정의보단 스위치가 하는 역할에 조금 더 가까운 것 같습니다.
스위치의 정의 대신 스위치의 역할로 텍스트를 바꾸는 건 어떨까요??

2024-04-12 16:26 UTC, k2645 commented on Computer Science/Network/3. 네트워크의 기기.md
> +기본적으로 Processor, RAM, OS를 탑재하므로 많은 부가 기능을 갖는다.
목록을 표시하는 `-`이 빠진 것 같습니다!

2024-04-12 16:26 UTC, k2645 commented on Computer Science/Network/3. 네트워크의 기기.md
> +- 노드의 수가 증가해도 속도의 저하가 일어나지 않으며, 패킷의 감청이 어려운 구조이므로 보안성이 높다.
해당 내용은 스위치의 특징보다는 스위치의 장점에 더 부합하는 내용인 것 같다는 생각이 듭니다! 어떻게 생각하시나요??

2024-04-12 16:26 UTC, k2645 commented on Computer Science/Network/3. 네트워크의 기기.md
> +- L2는 MAC주소, L3은 프로토콜(IP) 주소, L4는 세션 프로토콜을 이용하여 스위칭할 수 있다.
스위치에 대한 부분의 문체가 상단 문체와는 달라 어색하게 느껴지는 것 같습니다. 상단의 문체와 동일하게 간결체로 통일해서 적어주시면  좋을 것 같습니다!

2024-04-14 04:07 UTC, NewCodes7 commented on Computer Science/Network/3. 네트워크의 기기.md
> +- 스위칭은 정보 전달의 수단과 회선의 효율적 운용을 위해 입출력 사태를 감시하며, 전송로의 장애 발생 시 현재 상태에서 예비 상태로 전환한다.
맞네요!! 수정했습니다!

2024-04-14 04:07 UTC, NewCodes7 commented on Computer Science/Network/3. 네트워크의 기기.md
> +기본적으로 Processor, RAM, OS를 탑재하므로 많은 부가 기능을 갖는다.
수정했습니다!

2024-04-14 04:08 UTC, NewCodes7 commented on Computer Science/Network/3. 네트워크의 기기.md
> +- 노드의 수가 증가해도 속도의 저하가 일어나지 않으며, 패킷의 감청이 어려운 구조이므로 보안성이 높다.
다시 읽어보니 특징과 장점이 많이 겹쳐있네요! 장점으로 통합해서 작성했습니다!!

2024-04-14 04:08 UTC, NewCodes7 commented on Computer Science/Network/3. 네트워크의 기기.md
> +- L2는 MAC주소, L3은 프로토콜(IP) 주소, L4는 세션 프로토콜을 이용하여 스위칭할 수 있다.
동의합니다!! ㅎㅎ 간결체로 수정했습니다!

2024-04-14 04:09 UTC, NewCodes7 commented on Computer Science/Network/3. 네트워크의 기기.md
> +- L2는 MAC주소, L3은 프로토콜(IP) 주소, L4는 세션 프로토콜을 이용하여 스위칭할 수 있다.
영현님 자세한 피드백 감사드려요!! 가독성 더 향상되고, 덕분에 추가한 내용도 있습니다 ㅎㅎ

2024-04-14 05:32 UTC, k2645 approved these changes
수고하셨습니다.ᐟ.ᐟ

2024-04-16 07:59 UTC, merged