[네트워크] TCP/IP 4계층 자료 총정리
BCS-study/basic-computer-science pull request #13
Opened 2024-04-12 16:02 UTC by k2645

조금 늦게 올리게 되었습니다..죄송합니다ㅠㅜ
발표자료 전반적으로 정리 및 취합하였습니다. 오타 및 오류가 있다면 말씀해주세요 🙇🏻‍♀️

2024-04-14 05:05 UTC, NewCodes7 requested changes
깔끔하게 잘 정리되어있네요!! 수고 많으셨어요 ㅎㅎ

2024-04-14 05:05 UTC, NewCodes7 commented on Computer Science/Network/2. TCP IP 4계층 모델.md
> +- Initial Sequence Numbers의 약어, 초기 네트워크 연결을 할 때 할당횐 32비트 고유 시퀀스 번호
'할당횐 -> 할당한'으로 바꿔주시면 될 것 같습니다!

2024-04-14 05:05 UTC, NewCodes7 commented on Computer Science/Network/2. TCP IP 4계층 모델.md
> +
템플릿에 포함된 내용은 아니었지만, 목차를 추가해주시면 나중에 다시 모르는 개념 찾아볼 때 or 문서를 본격적으로 보기 전에 거시적으로 어떤 내용이 들어있는지 확인할 때 도움이 될 것 같습니다!! 

목차 만들어주는 툴을 첨부드립니다! vscode 사용하신다면 플러그인이 유용하실 겁니다!

1. https://ecotrust-canada.github.io/markdown-toc/
2. vscode 플러그인(Auto Markdown TOC): https://marketplace.visualstudio.com/items?itemName=xavierguarch.auto-markdown-toc

2024-04-14 05:45 UTC, k2645 commented on Computer Science/Network/2. TCP IP 4계층 모델.md
> +- Initial Sequence Numbers의 약어, 초기 네트워크 연결을 할 때 할당횐 32비트 고유 시퀀스 번호
수정했습니다!

2024-04-14 05:46 UTC, k2645 commented on Computer Science/Network/2. TCP IP 4계층 모델.md
> +
넵! 피드백 수용하여 목차 추가했습니다! 친절한 설명 감사합니다 :)

2024-04-14 06:31 UTC, NewCodes7 approved these changes
수고하셨어요!!

2024-04-15 14:28 UTC, minsu111 approved these changes
고생하셨습니다 !

2024-04-16 09:03 UTC, ukukdin commented
고생하셨습니다. ~

2024-04-17 04:49 UTC, OhHaneol commented
고생하셨습니다!

2024-04-17 04:51 UTC, OhHaneol approved these changes

2024-04-17 05:41 UTC, merged