[네트워크] 2주차 HTTP 발표자료 통합
BCS-study/basic-computer-science pull request #15
Opened 2024-04-19 07:19 UTC by OhHaneol

- 이미지 자료를 추가했습니다.
- 상혁님의 쿠키&세션 자료를 추가했습니다.

2024-04-20 04:39 UTC, k2645 requested changes
쿠키와 세션, HTTP의 응답과 요청 등 책에는 나오지 않았지만 알아두면 좋을 내용들인 것 같아 해당 내용들이 추가된 것이 정말 좋은 것 같습니다!
리뷰를 최대한 꼼꼼히 하긴 했지만 혹시 부족한 부분이 있을 수 있습니다. 마크다운 문서 작성하실 때 preview를 한 번씩 확인해 보면서 작성하시면 더 좋을 것 같습니다!
정말 수고하셨습니다 🙇🏻‍♀️🍀

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +
1주차 PR 작성시 상혁님이 제시해주신 건데, 목차도 포함되어 있으면 좋을 것 같습니다!
상혁님이 달아주셨던 리뷰 참조해드릴게요 ~
[1주차 목차 리뷰](https://github.com/BCS-study/basic-computer-science/pull/11#discussion_r1565119970)

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +- 개념: 웹에서 데이터를 주고받는 서버-클라이언트 모델의 프로토콜입니다.
이미지와 리스트 사이 한 줄 띄워주세요 ~

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +    - 예시: 상품 선택 후 구매 페이지에서 선택한 상품의 정보가 없어집니다.
예시가 2개 이상인 경우 `,`를 사용해서 한 줄에 적거나 `예시 1`, `예시 2` 이렇게 적으면 더 자연스러울 것 같습니다 !

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +    - 쿠키는 사용자가 따로 요청하지 않아도 브라우저가 Request시에 Request Header를 넣어서 자동으로 서버에 전송
개인적으로 해당 내용들은 쿠키의 역할 보다는 특징에 해당하는 내용들인 것 같다는 생각이 듭니다! 어떻게 생각하시나요??

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +    - 사용자에 대한 정보를 서버에 두기 때문에 쿠키보다 보안에 좋지만, 사용자가 많아질수록 서버 메모리를 많이 차지
아래 세션의 특징에 나오는 내용과 중복되는 내용입니다. 역할에서는 지워도 되지 않을까요??

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +    - 즉, 동접자 수가 많은 웹 사이트인 경우 서버에 과부하를 주게 되므로 성능 저하의 요인
아래 세션의 특징 부분에 위 내용과 함께 적어주면 더 이해하기 좋을 것 같습니다 !

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +    - 세션은 쿠키를 이용해서 session Id 만 저장하고 그것으로 구분해서 서버에서 처리하기 때문에 비교적 보안성이 좋습니다.
보안이라는 내용이 중복되어 나옵니다. 보안과 속도를 따로 분리해서 작성하는게 가독성 면에서 더 좋을 것 같다고 생각이 듭니다!

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +- 쿠키/세션은 `캐시`와 엄연히 다르다.
갑자기 '캐시'에 대한 내용이 나와서 살짝..뜬금없다는 생각이 들긴 하는 것 같습니당... '캐시'에 대한 내용도 같이 명시해주거나 조금..다르게 적어주는 것(ex 인용을 사용한다거나 기울임체를 쓴다거나...)은 어떨까요?? 어떻게 생각하시나욥??

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +### 쿠키와 세션
책에 나와있진 않지만 중요한 내용인 것 같습니다 .ᐟ.ᐟ 해당 내용을 추가한 건 정말 좋은 것 같습니다 .ᐟ.ᐟ 👍

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +## HTTP 응답
해당 내용도 책에 없지만 추가적으로 알아두면 정말 좋은 내용인 것 같네요!

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +    <img width="600" alt="image" src="https://github.com/BCS-study/basic-computer-science/assets/123712285/ad37bd98-131b-4da3-bb4a-302414259598">
해당 부분의 들여쓰기는 삭제해야할 것 같습니다!

2024-04-20 04:39 UTC, k2645 commented on Computer Science/Network/5. HTTP.md
> +- 개념: 하나의 연결 내 병렬적인 스트림으로 데이터를 운반합니다.
이미지 아래는 한 번 내려쓰기 해주세요 ~

2024-04-20 14:48 UTC, minsu111 requested changes
HTTP 특징, 메서드, 쿠키/세션 등 내용이 추가되어 좋네요. 고생하셨습니다!
영현님이 꼼꼼히 리뷰해 주셔서 저는 사소한 거 하나만 추가적으로 남겨두었습니다.
감사합니다 🙂

2024-04-20 14:48 UTC, minsu111 commented on Computer Science/Network/5. HTTP.md
> +---
구분선이 중복되어 삭제해 주셔도 괜찮을 것 같아요!

2024-04-20 16:13 UTC, NewCodes7 approved these changes
앞서 리뷰해주신 분들이 꼼꼼하게 해주셔서 크게 코멘트 남길 부분이 없네요 ㅎㅎ 정리하느라 수고하셨습니다!!

2024-04-20 16:13 UTC, NewCodes7 commented on Computer Science/Network/5. HTTP.md
> +- `인터셉터`: 공격자가 서버인 척하며 사용자 정보를 가로채는 행위
인터셉터 부분은 지워도 될 것 같다고 생각합니다! (아래 본문에서 '인터셉터' 단어 나오는 부분 있던데 거기서 잘 설명되어 있더라고요!)

인터셉터 단어 자체는 '공격'의 의미를 띄고 있다고 보기는 어려울 것 같습니다. 참고로 스프링에서는 인터셉터가 사용자 인증을 처리하는 데 도움을 주는 필터로써 쓰이곤 합니다. https://popo015.tistory.com/115 그래서 핵심 용어에 인터셉터를 위와 같이 정리하는 건 혼란을 유도할 수도 있을 것 같습니다!

2024-04-21 14:02 UTC, OhHaneol commented on Computer Science/Network/5. HTTP.md
> +    - 사용자에 대한 정보를 서버에 두기 때문에 쿠키보다 보안에 좋지만, 사용자가 많아질수록 서버 메모리를 많이 차지
쿠키와 세션의 양식을 비슷하게 만들기 위해 '역할과 특징'으로 정리해봤습니다!

2024-04-21 14:03 UTC, OhHaneol commented on Computer Science/Network/5. HTTP.md
> +    - 쿠키는 사용자가 따로 요청하지 않아도 브라우저가 Request시에 Request Header를 넣어서 자동으로 서버에 전송
역할과 특징이 모두 포함되는 것 같아서 역할과 특징으로 이름지었는데 괜찮을까요?

2024-04-21 14:13 UTC, OhHaneol commented on Computer Science/Network/5. HTTP.md
> +---
앗 이걸 놓쳤네요. 코멘트 감사합니다 수민님!

2024-04-21 14:16 UTC, OhHaneol commented on Computer Science/Network/5. HTTP.md
> +- `인터셉터`: 공격자가 서버인 척하며 사용자 정보를 가로채는 행위
앗 저도 적으면서 신기했던 부분인데요, 이 부분은 책 122페이지에서 그대로 발췌한 거라 스프링에서의 인터셉터와 네트워크상의 인터셉터의 의미가 다른 것 같습니다.
다만 상혁님 말씀대로 스프링과 네트워크상의 용어에 혼란을 유도하는 것 같아서, 앞에 '네트워크 상의'라고 괄호치는 것과 아예 삭제하는 것 중 어떤 게 좋을 지 의견 부탁드립니다!
좋은 코멘트 감사합니다!!

2024-04-21 14:25 UTC, OhHaneol commented on Computer Science/Network/5. HTTP.md
> +- 쿠키/세션은 `캐시`와 엄연히 다르다.
제가 `백틱`안에 표시한 용어들은 핵심 용어로 정리해뒀는데, 이 부분에 대한 설명이 부족한 듯 싶어 핵심 용어 아래에 부가 설명을 추가했습니다!
정성스런 코멘트 감사합니다 영현님!!
담부턴 더 꼼꼼하게 확인하겠습니다...🙇

2024-04-21 14:36 UTC, closed without merging