[운영체제] 1. 운영체제와 컴퓨터 발표 자료 최종
BCS-study/basic-computer-science pull request #17
Opened 2024-04-20 15:47 UTC by NewCodes7

늦게 올려 죄송합니다 ㅠㅠ 피드백 주시면 감사하겠습니다!!

2024-04-21 08:02 UTC, k2645 approved these changes
잘 작성해주셔서 피드백 드릴게 없는 것 같습니다 ! 정말 수고하셨습니다 ~ !

2024-04-22 02:21 UTC, minsu111 requested changes
고생하셨습니다🙂

이미지 출처에 아래 링크들 추가 부탁드리겠습니다!
- https://www.techtarget.com/whatis/definition/operating-system-OS
- https://www.almabetter.com/bytes/articles/list-of-operating-system
- https://velog.io/@oen/시스템콜-CPU-Protection-Rings-사용자모드-커널모드

2024-04-22 02:26 UTC, NewCodes7 commented
> 고생하셨습니다🙂
> 
> 이미지 출처에 아래 링크들 추가 부탁드리겠습니다!
> 
> * https://www.techtarget.com/whatis/definition/operating-system-OS
> * https://www.almabetter.com/bytes/articles/list-of-operating-system
> * [https://velog.io/@oen/시스템콜-CPU-Protection-Rings-사용자모드-커널모드](https://velog.io/@oen/%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%BD%9C-CPU-Protection-Rings-%EC%82%AC%EC%9A%A9%EC%9E%90%EB%AA%A8%EB%93%9C-%EC%BB%A4%EB%84%90%EB%AA%A8%EB%93%9C)

이미지 출처를 포함시키는 걸 깜빡했네요! 피드백 감사합니다!! 추가했습니다!

2024-04-22 02:28 UTC, minsu111 approved these changes

2024-04-23 06:16 UTC, OhHaneol commented
고생하셨습니다!

2024-04-23 06:18 UTC, ohahsis approved these changes

2024-04-23 06:33 UTC, merged