Network
BCS-study/basic-computer-science pull request #22
Opened 2024-04-23 13:43 UTC by ukukdin

수민님 IP 괜찮아서 가져왔습니다.

2024-04-24 02:02 UTC, NewCodes7 approved these changes

2024-04-24 02:02 UTC, NewCodes7 commented on Computer Science/Network/4. IP 주소.md
> +- IP 주소: 컴퓨터 또는 네트워크 장치를 식별하는 데 사용되는 주소.
. 빼주셔도 될 것 같습니다!

2024-04-24 04:18 UTC, minsu111 requested changes
고생하셨습니다 !

2024-04-24 04:18 UTC, minsu111 commented on Computer Science/Network/4. IP 주소.md
> +> \- **MAC 주소**: 컴퓨터 등 네트워크 기기 내 LAN 카드를 구별하기 위한 식별 번호 <br> > \- **브로드캐스트**: 송신 호스트가 전송한 데이터가 네트워크에 연결된 모든 호스트에 전송되는 방식 <br> > \- **유니캐스트**: 고유 주소로 식별된 하나의 호스트에 1:1로 데이터를 전송하는 방식 <br> > \- **ARP 테이블*
해당 부분은 아래 리뷰에서 논의된 것처럼 이번 모임 때 템플릿이 잡힌 이후 수정되면 좋을 것 같아요!
https://github.com/BCS-study/basic-computer-science/pull/20#discussion_r1574245986

그리고 저도 잘못 기입한 부분인데,
전체적으로 용어 설명에 '>'가 잘못 들어가 있는 부분들이 있어 이부분도 수정되면 좋을 것 같습니다.

2024-04-24 04:19 UTC, minsu111 approved these changes

2024-04-25 10:07 UTC, k2645 requested changes
수고하셨습니다!

2024-04-25 10:07 UTC, k2645 commented on .idea/workspace.xml
해당 파일은 PR에서 제외시켜주셔야 할 것 같습니다!

2024-04-25 10:07 UTC, k2645 commented on Computer Science/Network/4.IP 주소
이 파일도 같이 삭제해주시면 감사하겠습니다!

2024-04-25 10:07 UTC, k2645 commented on Computer Science/Network/4. IP 주소.md
> +
목차 부분이 생략된 것 같습니다. 목차도 추가해주시면 감사하겠습니다!

2024-04-25 12:54 UTC, closed without merging