[인터뷰] 3주 차 운영체제 인터뷰 질문 취합
BCS-study/basic-computer-science pull request #30
Opened 2024-04-27 10:24 UTC by NewCodes7

3주 차 운영체제 인터뷰 질문 정리했습니다!
사소한 거라도 피드백 있으시면 코멘트 남겨주세요!!

2024-04-27 12:14 UTC, ukukdin approved these changes

2024-04-28 12:05 UTC, OhHaneol approved these changes
잘 취합해주셔서 코멘트 할 게 없습니다. 고생하셨습니다!

2024-04-28 15:44 UTC, minsu111 requested changes
고생하셨습니다!!
소소한 코멘트 몇 개 남겼습니다 🙂

2024-04-28 15:44 UTC, minsu111 commented on Computer Science/Operating System/interview.md
> + ‘레지스터, 캐시, 주기억장치(RAM), 보조기억장치(HDD, SSD)’ + ‘휘발성, 속도, 기억 용량’
사소한 거지만 작은 따옴표가 들어갔네요!

2024-04-28 15:44 UTC, minsu111 commented on Computer Science/Operating System/interview.md
> +<summary>가상메모리는 무엇이며, MMU는 무엇인지 설명해주세요..</summary>
마침표가 두 개 찍혀서 아련해 보여요..! 😆

2024-04-28 15:44 UTC, minsu111 commented on Computer Science/Operating System/interview.md
> +가상메모리는 RAM의 크기를 실제보다 크게 확장하는 기술입니다. 이를 통해 프로세스 전체가 메모리 내에 올라오지 않더라도 실행이 가능하도록 합니다. 이를 통해 더 많은 프로그램이 동시에 실행될 수 있고, 프로그램들 간의 메모리 사용이 효율적으로 관리될 수 있습니다.
긴 문장을 이어 붙이면 가로 스크롤이 길어져서, 개행 적용하면 가독성 측면에서 더 좋을 것 같아요
아래 문항들도 전체적으로 한 번 봐주시면 좋을 것 같습니다!

2024-04-28 15:44 UTC, minsu111 commented on Computer Science/Operating System/interview.md
> +```
1. 해당 문항에서 혼용되는 워딩을 통일하면 좋을 것 같아요!
- 멀티 스레드/멀티 스레딩
- 멀티 프로세스/멀티 프로세싱

2. 크게 상관 없을 수 있지만 답변 순서도 질문에 따라 맞추면 어떨까요?
(멀티스레드 설명하고 멀티프로세스 설명하는 순서로)

2024-04-29 03:58 UTC, k2645 approved these changes
수민님께서 꼼꼼하게 코멘트를 남겨주셔서 따로 추가할 코멘트는 없어보입니다! 수고하셨습니다.ᐟ.ᐟ

2024-05-02 06:07 UTC, NewCodes7 commented on Computer Science/Operating System/interview.md
> + ‘레지스터, 캐시, 주기억장치(RAM), 보조기억장치(HDD, SSD)’ + ‘휘발성, 속도, 기억 용량’
수정했습니다!!

2024-05-02 06:07 UTC, NewCodes7 commented on Computer Science/Operating System/interview.md
> +<summary>가상메모리는 무엇이며, MMU는 무엇인지 설명해주세요..</summary>
수정했습니다!!

2024-05-02 06:09 UTC, NewCodes7 commented on Computer Science/Operating System/interview.md
> +가상메모리는 RAM의 크기를 실제보다 크게 확장하는 기술입니다. 이를 통해 프로세스 전체가 메모리 내에 올라오지 않더라도 실행이 가능하도록 합니다. 이를 통해 더 많은 프로그램이 동시에 실행될 수 있고, 프로그램들 간의 메모리 사용이 효율적으로 관리될 수 있습니다.
넵!! 전체적으로 다시 확인하며 반영했습니다!

2024-05-02 06:09 UTC, NewCodes7 commented on Computer Science/Operating System/interview.md
> +```
넵 이 부분도 수정했습니다!

2024-05-02 06:10 UTC, NewCodes7 commented on Computer Science/Operating System/interview.md
> +```
꼼꼼한 피드백 감사합니다!! ㅎㅎ

2024-05-02 06:32 UTC, minsu111 commented on Computer Science/Operating System/interview.md
> +```
모두 확인했습니다 고생하셨습니다 : )

2024-05-02 06:32 UTC, minsu111 approved these changes

2024-05-02 07:10 UTC, merged