2주차 네트워크ip
BCS-study/basic-computer-science pull request #31
Opened 2024-04-27 11:17 UTC by ukukdin

네트워크 ip .xml 파일 삭제 하고 다시 올립니다.

2024-04-27 14:59 UTC, ukukdin commented
운영체제 CPU 스케줄링 알고리즘도 포함되어있습니다.

2024-04-28 04:11 UTC, NewCodes7 requested changes
수고하셨습니다!

2024-04-28 04:11 UTC, NewCodes7 commented on Computer Science/Operating System/[운영체제] CPU 스케줄링 알고리즘.md
> +# 3.4 CPU 스케줄링 알고리즘
파일이름이랑 여기 '4. CPU 스케줄링 알고리즘'으로 수정해주세요!

2024-04-28 04:11 UTC, NewCodes7 commented on Computer Science/Operating System/[운영체제] CPU 스케줄링 알고리즘.md
> +  운영체제는 실행할 준비가 된 프로세스들이 적절히 CPU를 배정받아 효율적으로 작업을 처리할 수 있도록 관리해야 하고,<br>이를 위해서 다양한 스케줄링 알고리즘을 활용합니다.<br> 또한 스케줄링 알고리즘의 성능 평가 기준과 함께 여러 가지 스케줄링 기법에 대하여 살펴봅니다.
```suggestion
  운영체제는 프로세스들이 적절히 CPU를 배정받아 효율적으로 작업을 처리할 수 있도록 관리해야 합니다. <br>이를 위해서 다양한 스케줄링 알고리즘을 활용합니다.<br> 여러 가지 스케줄링 기법과 성능에 대해 살펴봅니다.
```
이렇게 고치면 어떨까요?? 개요 부분은 최대한 읽기 쉽게 작성하는 게 좋을 것 같아서요!

2024-04-28 04:11 UTC, NewCodes7 commented on Computer Science/Operating System/[운영체제] CPU 스케줄링 알고리즘.md
> +- 섬전형 방식  : 현대 운영체제가 쓰는 방식으로 지금 사용하고 있는 프로세스를 알고리즘에 의해 중단시키고 버리고 강제로 다른 프로세스에 CPU 소유권을 할당하는 방식을 말합니다.
```suggestion
- 섬전형 방식  : 현대 운영체제가 쓰는 방식으로 지금 사용하고 있는 프로세스를 알고리즘에 의해 중단시키고 강제로 다른 프로세스에 CPU 소유권을 할당하는 방식을 말합니다.
```
'버리고'는 빼도 될 것 같습니다!

2024-04-28 11:45 UTC, ohahsis commented
고생하셨습니다!

2024-04-28 15:52 UTC, minsu111 approved these changes
고생하셨습니다 🙂
상혁님이 코멘트 남겨주신 부분 반영되면 좋을 것 같네요!

2024-04-29 04:08 UTC, k2645 requested changes
수고하셨습니다!

2024-04-29 04:08 UTC, k2645 commented on Computer Science/Network/4.IP 주소.md
> +- RARP: ARP와 반대로 물리 주소인 MAC 주소를 논리 주소인 IP 주소로 변환하는 프로토콜
저희가 정했던 발표자료 취합 템플릿대로 핵심용어에 백틱 '`'을 달아주시면 감사하겠습니다!
추가로 IP 주소의 설명에만 마침표가 있는데 해당 마침표는 삭제하면 좋을 것 같습니다.

2024-04-29 04:08 UTC, k2645 commented on Computer Science/Network/4.IP 주소.md
> +
목차 추가해주시면 감사하겠습니다!

2024-04-29 04:08 UTC, k2645 commented on Computer Science/Network/4.IP 주소.md
> +**IP 주소**는 인터넷에 연결되어 있는 모든 호스트나 라우터 장비의 인터페이스에 할당된 **논리적인 주소**이며, 네트워크에서 데이터를 전송할 때 출발지와 목적지를 식별하는 데 사용되고 IP 주소를 통해 데이터 패킷이 올바른 목적지로 전송되는것입니다.
전반적으로 '-입니다.' 로 끝나는 문장들을 '-이다.' 와 같이 간결체로 수정해주시면 감사하겠습니다!

2024-04-29 04:08 UTC, k2645 commented on Computer Science/Network/4.IP 주소.md
> +    - 네트워크 외부와 통신하는 데 사용되는 IP 주소
이는 Public IP의 의미에 해당하는 내용임으로 앞에 '의미:'를 추가해주시면 좋을 것 같습니다. 

하단 내용들도 마찬가지로 저희가 저번 회의때 정했던 템플릿과 마찬가지로 특징 혹은 의미 등 서술의 범주를 내용 앞단에 추가로 작성해주시면 감사하겠습니다

2024-05-07 23:10 UTC, closed without merging