[운영체제] 프로세스와 스레드 발표자료 통합
BCS-study/basic-computer-science pull request #33
Opened 2024-04-27 13:54 UTC by OhHaneol

- 이미지와 설명을 추가했습니다.
- 핵심 용어와 그 외의 용어를 분리했습니다.

코멘트 주시면 감사하겠습니다!

2024-04-28 04:16 UTC, NewCodes7 approved these changes
좋습니다! 크게 코멘트 드릴 부분은 없네요!! 양 많은데 정리하느라 수고하셨습니다!!

2024-04-28 15:53 UTC, minsu111 approved these changes
고생하셨습니다 🙂

2024-04-29 04:14 UTC, k2645 requested changes
정말 수고 많으셨습니다! 조그마한 수정사항 외엔 잘 작성해주신 것 같습니다.ᐟ.ᐟ

2024-04-29 04:14 UTC, k2645 commented on Computer Science/Operating System/3. 프로세스와 스레드.md
> +    - [어셈블리어](#어셈블리어)로 변환한다.
저번 회의때 정한 템플릿대로 이렇게 설명이 필요한 단어는해당 내용이 나오는 문단 끝에 인용으로 작성해주시면 감사하겠습니다.ᐟ.ᐟ 
하단에 그 외 용어에 나오는 다른 단어들도  마찬가지로 인용을 활용하여 해당 내용이 나오는 문단 하단에 작성하는 식으로 수정해주시면 정말 감사하겠습니다!

2024-04-29 08:48 UTC, OhHaneol commented on Computer Science/Operating System/3. 프로세스와 스레드.md
> +    - [어셈블리어](#어셈블리어)로 변환한다.
넵 해당 사항 반영했습니다! 확인해주시면 감사하겠습니다!😃

2024-04-30 05:19 UTC, k2645 approved these changes
수고하셨습니다.ᐟ.ᐟ 👍

2024-04-30 09:19 UTC, merged