[데이터베이스] 2. ERD와 정규화 과정 발표 자료 첨삭 및 PR
BCS-study/basic-computer-science pull request #34
Opened 2024-05-03 00:55 UTC by NewCodes7

피드백 있으시면 코멘트 얼마든지 남겨주세요!!

* 정규화 과정에 대해서 다들 좋은 예시 이미지 들어주셨습니다! 깔끔한 인터페이스를 가진 이미지도 많았지만, 제가 발표할 당시 이미지로 그대로 둔 이유는 '종속 관계'까지 그림에 포함되어 있어 이해하기 더 쉬울 것 같아서입니다!

2024-05-04 06:27 UTC, minsu111 requested changes
고생하셨습니다! 말씀하신 대로 예시에 종속 관계까지 포함되어 있어서 더 좋은 것 같아요👍

다른 건 피드백 드릴 게 없는 것 같고,
‘~입니다.’와 같은 높임체과 반말체가 혼용되어 있어 이 부분만 통일해주시면 좋을 것 같습니다!

근데 저희 이전 발표 자료들도 섹션에 따라 두 문체가 혼용되어 있는데, 어떤 걸로 맞추는 게 좋을까요?
이 부분은 명확히 하지 않았던 것 같은데, 제가 놓친 걸 수도 있어 여쭤봅니다~

2024-05-04 08:07 UTC, k2645 requested changes
ERD 표기법에서 키의 관계를 이미지로 보여주셔서 더 이해하기 쉬워진 것 같습니다. 정말 수고하셨습니다!

2024-05-04 08:07 UTC, k2645 commented on Computer Science/Database/2. ERD와 정규화 과정.md
> +### 이상 현상 (예시)
수민님께서 남겨주신 리뷰처럼 해당 내용 아래로 높임말을 사용하고 있어서 이것들을 '-이다'와 같은 간결체로 바꿔주시면 좋을 것 같습니다!

2024-05-04 10:28 UTC, OhHaneol commented
이미지가 적절히 사용돼서 이해하기 쉬운 것 같습니다. 고생하셨습니다 :)

2024-05-04 10:41 UTC, OhHaneol commented on Computer Science/Database/2. ERD와 정규화 과정.md
> +    - 혹은 릴레이션에 데이터를 삽입할 때 의도와는 상관없이 원하지 않은 값들도 함께 삽입되는 현상을 '삽입 이상'이라고 합니다.
구체적인 예시가 나와서 좋은 것 같습니다!
혹시 개념이 첫 번째 줄에 먼저 나오고, 이후 예시에 대해 설명하는 방식은 어떻게 생각하시는지 문의드립니다!

2024-05-04 10:41 UTC, OhHaneol commented on Computer Science/Database/2. ERD와 정규화 과정.md
> +- 예시
이해하기 좋은 자료 같아요 👍

2024-05-04 10:41 UTC, OhHaneol commented on Computer Science/Database/2. ERD와 정규화 과정.md
> +        <img width="700" alt="image" src="https://github.com/BCS-study/basic-computer-science/assets/123712285/f5223d1c-9476-4a98-9ef8-52d9c06d4523">
- '교수' 가 '특강 이름' 에 대해 결정자이지만 후보키가 아니다.
- '교수'가 후보키가 되도록 테이블을 분리한다.

이런 식으로 설명을 추가하면 어떨까요?

2024-05-06 08:12 UTC, NewCodes7 commented on Computer Science/Database/2. ERD와 정규화 과정.md
> +### 이상 현상 (예시)
넵 간결체로 통일했습니다!

2024-05-06 08:12 UTC, NewCodes7 commented on Computer Science/Database/2. ERD와 정규화 과정.md
> +    - 혹은 릴레이션에 데이터를 삽입할 때 의도와는 상관없이 원하지 않은 값들도 함께 삽입되는 현상을 '삽입 이상'이라고 합니다.
넵 그게 더 좋은 것 같네요!! 반영했습니다!

2024-05-06 08:13 UTC, NewCodes7 commented on Computer Science/Database/2. ERD와 정규화 과정.md
> +        <img width="700" alt="image" src="https://github.com/BCS-study/basic-computer-science/assets/123712285/f5223d1c-9476-4a98-9ef8-52d9c06d4523">
넵 훨씬 이해하기 수월할 것 같네요! 이도 반영했습니다!! 피드백 감사합니다!!

2024-05-06 08:14 UTC, NewCodes7 commented
@minsu111 '~이다.'와 같은 간결체로 통일했습니다! 다들 이렇게 작성해주셨고, 이게 문서화하는 데 더 깔끔한 것 같아 피드백 반영했습니다!!

2024-05-06 10:54 UTC, OhHaneol approved these changes

2024-05-07 04:41 UTC, minsu111 approved these changes

2024-05-07 12:26 UTC, k2645 approved these changes

2024-05-07 12:47 UTC, merged