[데이터베이스] 데이터베이스의 기본 발표자료 총정리
BCS-study/basic-computer-science pull request #35
Opened 2024-05-03 08:25 UTC by k2645

- 데이터베이스 모델에 대한 내용을 추가하였습니다.
- 스키마에 대한 내용을 추가하였습니다.
- DBMS와 데이터베이스 시스템에 대한 내용을 추가하였습니다.

수정이 필요한 부분이나 내용이 틀린 부분이 있다면 말씀해주세요! :)

2024-05-04 04:36 UTC, NewCodes7 approved these changes
수고하셨습니다!! 정리 꼼꼼하게 잘해주신 게 느껴집니다!

2024-05-04 04:36 UTC, NewCodes7 commented on Computer Science/Database/1. 데이터베이스의 기본.md
> +        - `TEXT`와 `BLOB` 모두 큰 데이터를 저장할 떄 쓰는 타입이다.
떄 -> 때 오타 있네요!

2024-05-04 04:36 UTC, NewCodes7 commented on Computer Science/Database/1. 데이터베이스의 기본.md
> +
<img width="500" alt="image" src="https://github.com/BCS-study/basic-computer-science/assets/123712285/dd33ee18-b52c-4d4f-a5e8-8ed8a5d8bb21"> 

출처: [https://ddecode.tistory.com/entry/데이터베이스DB-4관계형-데이터베이스의-키key의-종류](https://ddecode.tistory.com/entry/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4DB-4%EA%B4%80%EA%B3%84%ED%98%95-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%9D%98-%ED%82%A4key%EC%9D%98-%EC%A2%85%EB%A5%98)

해당 이미지도 넣어주시면 키 개념 구조화하는 데 도움될 것 같습니다!!

2024-05-04 06:29 UTC, minsu111 approved these changes
고생하셨습니다 : )

2024-05-04 08:12 UTC, k2645 commented on Computer Science/Database/1. 데이터베이스의 기본.md
> +
242번째 줄 보면 키의 관계에 대한 이미지가 첨부되어있습니다!
rich diff로 보면 가끔 이미지가 잘 보이지 않을 때가 있는 것 같더라구요..

2024-05-04 10:13 UTC, NewCodes7 commented on Computer Science/Database/1. 데이터베이스의 기본.md
> +
그렇군요! 추가되어 있네요 ㅎㅎ 확인 감사합니다!

2024-05-04 10:21 UTC, OhHaneol commented
표랑 이미지가 적절하게 사용돼서 이해하기 좋은 것 같습니다. 고생 많으셨습니다 :D

2024-05-04 10:22 UTC, OhHaneol requested changes

2024-05-04 10:22 UTC, OhHaneol commented on Computer Science/Database/1. 데이터베이스의 기본.md
> +        - `SET`은 **비트 단위의 연산**을 할 수 있으며 회대 64개의 요소를 집어넣을 수 있다.
회대 -> 최대로 수정 부탁드려요!

2024-05-07 12:26 UTC, k2645 commented on Computer Science/Database/1. 데이터베이스의 기본.md
> +        - `SET`은 **비트 단위의 연산**을 할 수 있으며 회대 64개의 요소를 집어넣을 수 있다.
수정했습니다!

2024-05-07 12:27 UTC, OhHaneol approved these changes

2024-05-07 12:28 UTC, merged