[데이터베이스] 4주차 인터뷰 질문 통합
BCS-study/basic-computer-science pull request #37
Opened 2024-05-04 10:12 UTC by OhHaneol

- 질문과 답변의 어투를 통일했습니다.

피드백이 있으시다면 코멘트 남겨주세요!!

2024-05-05 06:50 UTC, minsu111 requested changes
고생하셨습니다!👍
잘 정리해주셔서 크게 피드백 드릴 부분은 없지만 사소한 코멘트 몇 개 남깁니다~

2024-05-05 06:50 UTC, minsu111 commented on Computer Science/Database/interview.md
> +- [4.1 데이터베이스의 기본](https://github.com/OhHaneol/basic-computer-science/blob/main/Computer%20Science/Database/1.%20%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%9D%98%20%EA%B8%B0%EB%B3%B8.m
'4.1' 과 같이 넘버링 되어있는 부분은 '1. 데이터베이스의 기본' 이런식으로 통일해주시면 좋을 것 같아요!

2024-05-05 06:50 UTC, minsu111 commented on Computer Science/Database/interview.md
> +- [데이터베이스의 기본](1.%20데이터베이스의%20기본.md)
마찬가지로 관련 자료에 저희 발표 자료가 기재된 경우 넘버링 추가해서 통일하면 좋을 것 같습니다~

2024-05-05 06:50 UTC, minsu111 commented on Computer Science/Database/interview.md
> +릴레이션의 분해로 인해 릴레이션 간의 연산(JOIN 연산)이 많아진다. 이로인해 질의에 대한 응답 시간이 느려질 수 있다.
해당 문항도 문체 통일 부탁드립니다.

2024-05-06 08:23 UTC, NewCodes7 requested changes
정리하느라 수고하셨습니다! 코멘트 한번 봐주시면 감사하겠습니다!!

2024-05-06 08:23 UTC, NewCodes7 commented on Computer Science/Database/interview.md
> +N:M 관겨의 경우 1:N(일대다) 관계와 비슷하지만, 양방향에서 다수의 레코드를 가질 수 있다는 특징이 있습니다.
관겨 -> 관계

오타있네요!

2024-05-06 08:23 UTC, NewCodes7 commented on Computer Science/Database/interview.md
> +- [4.2 ERD와 정규화 과정](https://github.com/OhHaneol/basic-computer-science/blob/main/Computer%20Science/Database/2.%20ERD%EC%99%80%20%EC%A0%95%EA%B7%9C%ED%99%94%20%EA%B3%BC%EC%A0%95.md#%EC%A0%95%EA%B7%9C
링크를 원본 저장소의 md 파일로 걸어두면 될 것 같습니다!

- [ERD와 정규화 과정](2.%20ERD와%20정규화%20과정.md)

이런 식으로 작성해두면 원본 저장소로 되더라고요~

2024-05-06 08:23 UTC, NewCodes7 commented on Computer Science/Database/interview.md
> +하나의 트랜잭션은 Commit(작업완료)되거나 Rollback(취소)됩니다.
트랜잭션이란 데이터베이스에서 수행되는 작업의 단위를 말합니다. 
이 작업은 한 번에 완전히 수행되거나 전혀 수행되지 않아야 합니다. 이는 커밋과 롤백으로 구현됩니다.
트랜잭션은 데이터베이스의 무결성을 보장하기 위해 중요하며, ACID 속성을 준수해야 합니다.

이런 식으로 바꿔보는 건 어떨까요? 트랜잭션에 대한 핵심의미가 제대로 담기진 않은 것 같아서 제안드려봅니다!

2024-05-06 10:49 UTC, OhHaneol commented on Computer Science/Database/interview.md
> +하나의 트랜잭션은 Commit(작업완료)되거나 Rollback(취소)됩니다.
다시 보니 말씀대로 의미가 잘 담기지 않은 것 같아서 수정했습니다~!
코멘트 감사합니다!

2024-05-06 10:51 UTC, OhHaneol commented on Computer Science/Database/interview.md
> +릴레이션의 분해로 인해 릴레이션 간의 연산(JOIN 연산)이 많아진다. 이로인해 질의에 대한 응답 시간이 느려질 수 있다.
앗 이걸 놓쳤네요..! 넘버링 포함해서 의견 주신 부분 수정 완료했습니다!
꼼꼼한 코멘트 감사합니다!

2024-05-07 04:43 UTC, minsu111 approved these changes

2024-05-07 12:32 UTC, k2645 requested changes
수고하셨습니다 !

2024-05-07 12:32 UTC, k2645 commented on Computer Science/Database/interview.md
> +반명 VARCHAR의 경우 가변 길이 문자열로 입력된 데이터에 따라 용량을 가변시켜 저장합니다.
반명 -> 반면으로 오타가 난 것 같습니다! 수정해주세요 !

2024-05-07 12:49 UTC, NewCodes7 approved these changes
수고하셨습니다!!

2024-05-07 12:53 UTC, OhHaneol commented on Computer Science/Database/interview.md
> +반명 VARCHAR의 경우 가변 길이 문자열로 입력된 데이터에 따라 용량을 가변시켜 저장합니다.
수정 완료했습니다! 감사합니다!

2024-05-11 06:51 UTC, merged