[데이터베이스] 5주 차 인터뷰 취합
BCS-study/basic-computer-science pull request #41
Opened 2024-05-11 06:53 UTC by NewCodes7

5주 차 인터뷰 취합했습니다!

수정할 부분 있다면 코멘트 남겨주세요~~!

2024-05-12 12:04 UTC, OhHaneol approved these changes
따로 코멘트 드릴 게 없습니다! 정리해주셔서 감사합니다 :)

2024-05-12 13:00 UTC, minsu111 approved these changes
고생하셨습니다! 저도 따로 코멘트 드릴 부분이 없네요. 정리 감사합니다 : )

2024-05-14 10:54 UTC, k2645 requested changes
질문 몇 개 겹치는 것에 대한 피드백 드렸습니다 ! 정말 수고하셨습니다 !

2024-05-14 10:54 UTC, k2645 commented on Computer Science/Database/interview.md
> +반면 NoSQL은 컬렉션이라는 형태로 데이터를 관리하며, 데이터간의 관계를 정의하지 않고, 스키마가 없어 좀 더 자유롭게 데이터를 관리할 수 있습니다.
스키마가 없다기 보다는 동적 스키마를 사용한다고 정정하는게 어떨까요?

2024-05-14 10:54 UTC, k2645 commented on Computer Science/Database/interview.md
> +</details>
해당 질문은 위에 '데이터베이스에서의 index에 대해 설명해주세요'와 겹치는 질문인 것 같습니다! 하나는 삭제해도 좋을 것 같습니다!

2024-05-14 10:54 UTC, k2645 commented on Computer Science/Database/interview.md
> +```
해당 질문 또한 위 RDBMS와 NoSQL의 차이점에 대해 물어보는 질문과 겹치는 것 같아 하나로 합치면 좋을 것 같습니다 !

2024-05-18 01:15 UTC, NewCodes7 commented on Computer Science/Database/interview.md
> +반면 NoSQL은 컬렉션이라는 형태로 데이터를 관리하며, 데이터간의 관계를 정의하지 않고, 스키마가 없어 좀 더 자유롭게 데이터를 관리할 수 있습니다.
정정했습니다!

2024-05-18 01:15 UTC, NewCodes7 commented on Computer Science/Database/interview.md
> +</details>
넵 하나는 삭제했습니다!

2024-05-18 01:15 UTC, NewCodes7 commented on Computer Science/Database/interview.md
> +```
네 하나로 병합했습니다!

2024-05-22 01:05 UTC, k2645 approved these changes

2024-05-22 12:31 UTC, merged