[1-2주차 발표자료] 정리
BCS-study/basic-computer-science pull request #43
Opened 2024-05-14 01:53 UTC by OhHaneol

- 문체를 통일했습니다.
- 개행 양식을 통일했습니다.
- 용어를 문단 아래로 옮겼습니다.

코멘트 주시면 감사하겠습니다!

2024-05-14 11:09 UTC, k2645 requested changes
템플릿을 깔끔하게 잘 적용해주신 것 같습니다 ! 문서화 작업하느라 수고하셨습니다 .ᐟ.ᐟ 피드백은 제 개인적인 의견에 대한 것만 몇몇 적어보았습니다 ! 제 생각에 대한 다른 분들의 의견도 달아주시면 감사하겠습니다 ! 🙇🏻‍♀️

2024-05-14 11:09 UTC, k2645 commented on Computer Science/Network/1. 네트워크의 기초.md
>  # 2.1 네트워크의 기초
아직 넘버링에 대한 건 자세히 정하지 않았던 것 같습니다 ! 일단 넘버링은 제거해놓는 것은 어떨까요??

2024-05-14 11:09 UTC, k2645 commented on Computer Science/Network/1. 네트워크의 기초.md
> +    - 네트워크 토폴로지는 네트워크 장치 간의 물리적 및 논리적 구성으로, 병목 현상을 찾을 때 중요한 기준이 된다.
이건 제 개인적인 생각입니다만, 이렇게 한 줄로 끝나는 의미나 개념의 경우는 ':' 표시를 사용하여 개행 목차를 넣지 않고 한 줄로 정리하는 게 더 깔끔할 것 같다는 생각입니다 ! 
특징과 같이 여러개를 나열해서 적어야하는 경우는 개행 목차를 사용하고 의미나 개념 등 한 줄로 표현 가능한 경우는  ':'을 사용하는 것에 대해 어떻게 생각하시나요 ??

2024-05-16 06:01 UTC, minsu111 commented on Computer Science/Network/1. 네트워크의 기초.md
> +    - 네트워크 토폴로지는 네트워크 장치 간의 물리적 및 논리적 구성으로, 병목 현상을 찾을 때 중요한 기준이 된다.
저도 말씀 주신 대로 통일되면 좋을 것 같습니다!

2024-05-16 06:24 UTC, minsu111 requested changes
1-2주차 발표자료까지 재점검하시느라 정말 고생하셨습니다🥺

2024-05-16 06:24 UTC, minsu111 commented on Computer Science/Network/1. 네트워크의 기초.md
> +    > - **대역폭**: 주어진 시간 동안 네트워크 연결을 통해 흐를 수 있는 최대 비트 수
인용문 앞단에 '-' 가 들어가 있는데, 다른 부분 수정해주실 때 함께 슥 수정해주시면 감사하겠습니다!

2024-05-16 06:24 UTC, minsu111 commented on Computer Science/Network/1. 네트워크의 기초.md
> +        > - **스푸핑**: LAN 상에서 송신부의 패킷을 송신과 관련 없는 다른 호스트에 가지 않도록 하는 것을 스위칭 기능이라고 하는데, 스푸핑은 이를 마비시키거나 속여서 특정 노드(악의적 노드)에 해당 패킷이 오도록 처리하는 것을 말합니다.
여기도 '-' 삭제 부탁드립니다~

2024-05-16 06:24 UTC, minsu111 commented on Computer Science/Network/1. 네트워크의 기초.md
> +## 목차
세 개 파일 모두 통일성을 위해 목차를 개요 상단으로 옮겨주시면 좋을 것 같습니다!

2024-05-16 06:57 UTC, k2645 commented on Computer Science/Network/1. 네트워크의 기초.md
> +    - 네트워크 토폴로지는 네트워크 장치 간의 물리적 및 논리적 구성으로, 병목 현상을 찾을 때 중요한 기준이 된다.
저도 수민님 의견이 좋은 것 같습니다 !

2024-05-19 13:52 UTC, OhHaneol commented on Computer Science/Network/1. 네트워크의 기초.md
> +## 목차
해당 부분 반영했습니다! 코멘트 감사합니다!

2024-05-19 13:53 UTC, OhHaneol commented on Computer Science/Network/1. 네트워크의 기초.md
> +    - 네트워크 토폴로지는 네트워크 장치 간의 물리적 및 논리적 구성으로, 병목 현상을 찾을 때 중요한 기준이 된다.
넵! 해당 부분 수민님 의견대로 유지하였습니다. 의견 감사합니다!

2024-05-22 01:06 UTC, k2645 approved these changes
리뷰 꼼꼼하게 반영해주셔서 감사합니다 :)

2024-05-22 12:32 UTC, NewCodes7 approved these changes
앞에서 다들 코멘트 잘 남겨주셨네요! 수고하셨습니다!!

2024-05-24 00:38 UTC, minsu111 approved these changes
고생하셨습니다 감사합니다 👍

2024-05-24 01:12 UTC, merged