CPU 스케줄링 알고리즘 + IP 주소
BCS-study/basic-computer-science pull request #45
Opened 2024-05-15 09:26 UTC by ukukdin

죄송합니다. 많이 늦어졌습니다. (변명을 하자면,.. 다음주까지 마감이라 팀원 전부가 매일매일 야근에 주말 출근중이네요...;;)

2024-05-19 01:50 UTC, k2645 requested changes
바쁘신 와중에 PR 올려주시느라 수고가 많으십니다 .ᐟ.ᐟ 
다만 저희가 정했던 템플릿들이 적용되지 않은 부분이 많이 보여서 해당 부분은 템플릿 문서를 확인하고 다른 파일들과 통일성 있게 수정해주시면 감사하겠습니다 🙇🏻‍♀️

2024-05-19 01:50 UTC, k2645 commented on Computer Science/Network/4.IP 주소.md
> +- **RARP: ARP와 반대로 물리 주소인 MAC 주소를 논리 주소인 IP 주소로 변환하는 프로토콜**
핵심 용어는 저희가 정한 템플릿대로 백틱 '`'을 사용해서 강조표시 해주시면 감사하겠습니다 !

2024-05-19 01:50 UTC, k2645 commented on Computer Science/Operating System/4. CPU 스케줄링 알고리즘.md
> +    - [다단계 큐](#qq)
목차는 다른 파일들과의 통일성을 위해 개요 위쪽에 위치시켜주시면 감사하겠습니다 !

2024-05-19 01:50 UTC, k2645 commented on Computer Science/Operating System/4. CPU 스케줄링 알고리즘.md
> +- **섬전형 방식  : 현대 운영체제가 쓰는 방식으로 지금 사용하고 있는 프로세스를 알고리즘에 의해 중단시키고 강제로 다른 프로세스에 CPU 소유권을 할당하는 방식을 말합니다.**
IP 주소 파일과 마찬가지로 저희가 정한 템플릿에 맞게 수정해주세요 ~

2024-05-19 01:50 UTC, k2645 commented on Computer Science/Operating System/4. CPU 스케줄링 알고리즘.md
해당 파일은 전반적으로 문체나 핵심용어 등 저희가 정한 템플릿이 적용되어있지 않은 것 같습니다 ! 템플릿 확인해보시고 그에 맞게 파일을 조금 수정하는 일이 필요해보입니다.

2024-05-19 01:50 UTC, k2645 commented on Computer Science/Network/4.IP 주소.md
> +**🧑‍💻\_관련 용어**
관련 용어가 있으니 더  좋아보이긴 하지만 다른 파일들과의 통일성을 위해 해당 제목은 없애는 것이 나아보입니다 !

2024-05-21 01:01 UTC, OhHaneol commented
많이 바쁘실텐데 고생하셨습니다..!
저도 영현님 의견만 반영된다면 좋을 것 같습니다!

2024-05-24 00:46 UTC, minsu111 requested changes
바쁘신데 정리하시느라 정말 고생 많으셨습니다!
위에 피드백 주신 부분 반영하여 전체적으로 저희 템플릿과 통일이 필요해보입니다.
덧붙여 '~합니다.'로 끝맺음 되어 있는 문장들도 '~이다.' 이런식으로 통일되면 좋겠네요🙂

2024-05-26 07:32 UTC, closed without merging