[네트워크] 3. 네트워크의 기기 템플릿 형식 수정
BCS-study/basic-computer-science pull request #48
Opened 2024-05-18 00:51 UTC by NewCodes7

1주 차 발표 자료를 템플릿 형식에 맞게 수정했습니다!

혹시 잘 안 된 부분이 있다면 코멘트 남겨주세요!!

2024-05-19 02:05 UTC, k2645 requested changes
수고하셨습니다 !

2024-05-19 02:05 UTC, k2645 commented on Computer Science/Network/3. 네트워크의 기기.md
>  ## 2.3.1 네트워크 기기의 처리 범위
해당 넘버링은 삭제하는게 좋을 것 같습니다!
파일 내부에 있는 넘버링 모두 없애는 것이 좋을 것 같아요 ~

2024-05-19 02:12 UTC, k2645 commented on Computer Science/Network/3. 네트워크의 기기.md
'목차'라는 헤더가 쓰여져 있지 않아서 '목차'헤더를 추가해주시면 좋을 것 같습니다 !

2024-05-21 00:47 UTC, OhHaneol requested changes

2024-05-21 00:47 UTC, OhHaneol commented on Computer Science/Network/3. 네트워크의 기기.md
> +- **구분 기준**: 어떤 주소를 통해 스위칭 하는지에 따라 L2,L3,L4 스위치로 구분한다.
고생하셨습니다!! 영현님이 잘 리뷰해주셔서, 저는 사소한 거 하나만 말씀드리자면
> L2, L3, L4
처럼 콤마 뒤에 띄어쓰기를 하면 좋을 것 같아요!

2024-05-24 00:37 UTC, minsu111 approved these changes
영현 님, 한얼 님이 피드백 주신 부분만 수정되면 좋을 것 같네요! 감사합니다~

2024-05-26 06:42 UTC, NewCodes7 commented
@k2645 @OhHaneol 늦어서 죄송합니다 ㅠㅠ 주신 피드백 모두 반영했습니다!!

2024-05-26 07:04 UTC, OhHaneol approved these changes

2024-05-27 05:58 UTC, k2645 approved these changes

2024-05-27 06:07 UTC, merged