[운영체제] 1. 운영체제와 컴퓨터 템플릿 형식 수정
BCS-study/basic-computer-science pull request #49
Opened 2024-05-18 00:55 UTC by NewCodes7

2024-05-19 02:11 UTC, k2645 requested changes
수고하셨습니다 .ᐟ.ᐟ

2024-05-19 02:11 UTC, k2645 commented on Computer Science/Operating System/1. 운영체제와 컴퓨터.md
목차를 쓰는 부분에 '목차'라는 헤더가 작성되어있지 않습니다 ! 헤더 하나만 추가해주시면 감사하겠습니다 !

2024-05-21 00:41 UTC, OhHaneol requested changes
고생하셨습니다! 저도 목차 헤더만 추가되면 좋을 것 같습니다.

2024-05-21 08:47 UTC, minsu111 approved these changes
고생하셨습니다!
헤더 이외에 따로 피드백 드릴 부분 없습니다~

2024-05-26 06:43 UTC, NewCodes7 commented
@k2645 @OhHaneol 늦어서 죄송합니다 ㅠㅠ 목차 헤더 추가했습니다!

2024-05-26 07:04 UTC, OhHaneol approved these changes

2024-05-27 05:58 UTC, k2645 approved these changes

2024-05-27 06:07 UTC, merged