IP 주소, CPU 스케줄링 알고리즘 작성
BCS-study/basic-computer-science pull request #53
Opened 2024-05-26 07:31 UTC by NewCodes7

IP 주소, CPU 스케줄링 알고리즘에 대해 템플릿 형식에 맞게 수정했습니다!

피드백 있으시면 남겨주세요!!

2024-05-26 12:31 UTC, OhHaneol requested changes
고생하셨습니다 😊
깔끔하게 정리해주셔서 사소한 오탈자만 코멘트 남겼습니다!

2024-05-26 12:31 UTC, OhHaneol commented on Computer Science/Network/4. IP 주소.md
> +  - IP 주소를 줄여서 IP라고 부르기도 하나 IP는 인터넷 규약 자체를 가리키에 엄밀하게는 구별해야 한다.
가리키에 -> 가리키기에 오타 수정 부탁드려요!

2024-05-26 12:31 UTC, OhHaneol commented on Computer Science/Operating System/4. CPU 스케줄링 알고리즘.md
> +- 특징: SJF 스케줄링에서 긴 시간을 가진 프로세스가 실행되지 않는 현상 해결한다.
현상 -> 현상을

수정 부탁드려요!

2024-05-26 12:31 UTC, OhHaneol commented on Computer Science/Operating System/4. CPU 스케줄링 알고리즘.md
> +- 의미: **중간에 더 짧은 작업**이 들어오면 수행하던 프로세스를 중지하고 해당 프로세를 수행하는 알고리즘이다.
프로세를 -> 프로세스를

수정 부탁드립니다!

2024-05-26 12:31 UTC, OhHaneol commented on Computer Science/Operating System/4. CPU 스케줄링 알고리즘.md
> +## 레퍼런스
타 발표자료와 같이, 레퍼런스 -> 참고자료 로 명칭 통일 해주시면 감사하겠습니다!

2024-05-27 03:30 UTC, ukukdin approved these changes

2024-05-27 06:04 UTC, k2645 approved these changes
한얼님께서 꼼꼼하게 리뷰해주셔서 따로 더 남길 리뷰는 없어보입니다 ! 정말 수고 많으셨습니다 🥹

2024-05-27 06:10 UTC, NewCodes7 commented
@OhHaneol 수정했습니다!! 피드백 주셔서 감사합니다 ㅎㅎ

2024-05-27 11:33 UTC, minsu111 approved these changes
고생하셨습니다👍

2024-05-27 14:22 UTC, OhHaneol approved these changes

2024-05-27 14:22 UTC, ohahsis commented
고생하셨습니다😃👍🏼

2024-05-27 23:11 UTC, merged